name: Image & Icon
slug: image
groups: general
helpId: 5d1ff01304286369ad8d5f04
form:
  general:
    - name : image_fields_group
      label: Image
      type: fields-group
      status: open
      schema:
        - name: image
          type: media
          showstyle: true
          value: 'media/quixnxt/images/placeholder.png'

        - name: alt_text
          label : Alt Text
          type: text
          help : Google focuses on alt text when trying to understand what an image is about. So it's valuable for SEO, in addition to being useful for users.
          depends:
            "image.type": image

        - name: caption
          type: text
          depends:
            "image.type": image

        - name: img_responsive
          label: Responsive
          type: switch
          value: true
          depends:
              "image.type": image

        - name : lightbox
          label: Lightbox
          type : switch
          value: false
          help: It will work when link is empty
          depends:
            "image.type": image

    - name : image_links_fields_group
      label: Link
      type: fields-group
      schema:
        - name: link
          label: Link Url
          type: link

  styles:
    - name    : image_fields_group
      label   : Image
      type    : fields-group
      status  : open
      schema  :
        - name : alignment
          type : choose
          responsive : true
          options:
            left :
              label: Left
              icon : qxuicon-align-left
            center :
              label : Center
              icon : qxuicon-align-center
            right :
              label : Right
              icon : qxuicon-align-right

        - name : width
          label : Width
          type: slider
          units: %, px
          defaultUnit: %
          max: 2000

        - name : opacity
          label : Opacity
          type: slider
          responsive : false
          max : 1
          step: 0.1
          units: %
          defaultUnit: %ss

    - name : border_fields_group
      label : Border
      type: fields-group
      schema :
        - name: img_border
          label: Border
          type: border
          popover: true

    - name    : icon_fields_group
      label   : Icon
      type    : fields-group
      schema  :
        - name: icon_hover_color
          label: Icon Hover Color
          type: color

        - name : icon_padding
          label : Padding
          type: dimensions

        - name: icon_background
          type: background
          label: Background Color
          popover: true

    - name    : caption_field_group
      label   : Caption
      type    : fields-group
      schema  :
        - name : caption_field_group_margin
          label : Margin
          type: dimensions

        - name : caption_field_group_padding
          label : Padding
          type: dimensions

        - name: caption_field_group_font
          label: Typography
          type: typography
          popover: true

        - name  : caption_field_group_text_color
          label : Text Color
          type  : color
          value: rgba(0, 0, 0, 0.8)

        - name  : caption_background_color
          label : Background Color
          type  : color

        - name  : caption_border
          label : Border
          type  : border
          popover: true
