INSERT INTO `#__app_sch_configuation` (`id`, `config_key`, `config_value`) VALUES
(1, 'download_id', ''),
(2, 'business_name', 'Services booking'),
(3, 'value_string_email_address', 'contact@osservicesbooking.com'),
(4, 'mobile_notification', ''),
(5, 'date_time_format', 'd.m.Y, H:i'),
(6, 'date_format', 'Y-m-d'),
(7, 'time_format', 'g:i A'),
(8, 'bootstrap_version', '0'),
(9, 'load_bootstrap', '1'),
(10, 'csv_separator', ';'),
(11, 'currency_format', 'USD'),
(12, 'currency_symbol_position', '1'),
(13, 'integrate_gcalendar', '0'),
(14, 'gcalendar_width', '700'),
(15, 'gcalendar_height', '600'),
(16, 'footer_content', 'Developed by Ossolution team'),
(17, 'meta_keyword', ''),
(18, 'meta_desc', ''),
(19, 'value_sch_reminder_enable', '0'),
(20, 'value_sch_reminder_email_before', '2'),
(21, 'employee_acl_group', ''),
(22, 'employee_change_availability', '0'),
(23, 'disable_timeslot', '0'),
(24, 'disable_venuetimeslot', '0'),
(25, 'multiple_work', '1'),
(26, 'limit_one_timeslot', '0'),
(27, 'booking_more_than_one', '0'),
(28, 'allow_registered_only', '2'),
(29, 'allow_registration', '1'),
(30, 'integrate_user_profile', '0'),
(31, 'group_payment', ''),
(32, 'step_format', '60'),
(33, 'disable_payments', '1'),
(34, 'enable_tax', '1'),
(35, 'tax_payment', '10'),
(36, 'deposit_type', '0'),
(37, 'deposit_payment', '25'),
(38, 'from_1', '0'),
(39, 'to_1', '0'),
(40, 'rate_1', '0'),
(41, 'from_2', '0'),
(42, 'to_2', '0'),
(43, 'rate_2', '0'),
(44, 'from_3', '0'),
(45, 'to_3', '0'),
(46, 'rate_3', '0'),
(47, 'from_4', '0'),
(48, 'to_4', '0'),
(49, 'rate_4', '0'),
(50, 'from_5', '0'),
(51, 'to_5', '0'),
(52, 'rate_5', '0'),
(53, 'allow_full_payment', '0'),
(54, 'early_bird', '0'),
(55, 'enable_slots_discount', '0'),
(56, 'disable_payment_order_status', 'P'),
(57, 'enable_cardtypes', 'Visa,MasterCard,Discover,Amex'),
(58, 'value_enum_email_confirmation', '2'),
(59, 'value_enum_email_payment', '1'),
(60, 'allow_multiple_timeslots', '0'),
(61, 'allow_cancel_request', '1'),
(62, 'allow_remove_items', '1'),
(63, 'cancel_before', '5'),
(64, 'use_qrcode', '1'),
(65, 'waiting_list', '0'),
(66, 'waiting_window_type', '0'),
(67, 'remove_confirmation_step', '0'),
(68, 'temporarily_time', '60'),
(69, 'active_comment', '0'),
(70, 'value_sch_include_phone', '1'),
(71, 'value_sch_include_country', '1'),
(72, 'default_country', ''),
(73, 'value_sch_include_city', '1'),
(74, 'value_sch_include_state', '1'),
(75, 'value_sch_include_zip', '0'),
(76, 'value_sch_include_address', '1'),
(77, 'value_sch_include_captcha', '1'),
(78, 'pass_captcha', '0'),
(79, 'enable_termandcondition', '0'),
(80, 'article_id', ''),
(81, 'activate_invoice_feature', '1'),
(82, 'send_invoice_to_customer', '1'),
(83, 'send_invoice_to_admin', '0'),
(84, 'invoice_prefix', 'IV'),
(85, 'invoice_number_length', '5'),
(86, 'invoice_format', '<table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" width=\"100%\">\r\n<table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td width=\"100%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\" width=\"50%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Company Name:</td>\r\n<td align=\"left\">Noname Company</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">URL:</td>\r\n<td align=\"left\">http://www.osservicesbooking.com</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Phone:</td>\r\n<td align=\"left\">123-456-789</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">E-mail:</td>\r\n<td align=\"left\">contact@osb.com</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Address:</td>\r\n<td align=\"left\">New York, NY, United States</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td align=\"right\" valign=\"middle\" width=\"50%\"><img style=\"border: 0px;\" src=\"images/logo.jpg\" alt=\"\" width=\"127\" height=\"118\" /></td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"2\" align=\"left\" width=\"100%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\" width=\"50%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td style=\"background-color: #d6d6d6;\" colspan=\"2\" align=\"left\">\r\n<h4 style=\"margin: 0px;\">Customer Information</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Name:</td>\r\n<td align=\"left\">[NAME]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Phone:</td>\r\n<td align=\"left\">[PHONE]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Email:</td>\r\n<td align=\"left\">[EMAIL]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Address:</td>\r\n<td align=\"left\">[ADDRESS], [CITY], [STATE], [COUNTRY]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td align=\"left\" valign=\"top\" width=\"50%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td style=\"background-color: #d6d6d6;\" colspan=\"2\" align=\"left\">\r\n<h4 style=\"margin: 0px;\">Invoice Information</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Invoice Number:</td>\r\n<td align=\"left\">[INVOICE_NUMBER]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Invoice Date:</td>\r\n<td align=\"left\">[INVOICE_DATE]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"background-color: #d6d6d6;\" colspan=\"2\" align=\"left\">\r\n<h4 style=\"margin: 0px;\">Order Items</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"2\" align=\"left\" width=\"100%\">\r\n<table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td colspan=\"4\">[DETAILS]</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"3\" align=\"right\" valign=\"top\" width=\"90%\">Discount :</td>\r\n<td align=\"left\" valign=\"top\" width=\"10%\">[DISCOUNT_AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"3\" align=\"right\" valign=\"top\" width=\"90%\">Subtotal :</td>\r\n<td align=\"left\" valign=\"top\" width=\"10%\">[SUB_TOTAL]</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"3\" align=\"right\" valign=\"top\" width=\"90%\">Tax :</td>\r\n<td align=\"left\" valign=\"top\" width=\"10%\">[TAX_AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"3\" align=\"right\" valign=\"top\" width=\"90%\">Total :</td>\r\n<td align=\"left\" valign=\"top\" width=\"10%\">[TOTAL_AMOUNT]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(87, 'enable_clickatell', '0'),
(88, 'clickatell_register', '0'),
(89, 'clickatell_username', ''),
(90, 'clickatell_password', ''),
(91, 'clickatell_api', '3419302'),
(92, 'clickatell_senderid', ''),
(93, 'enable_eztexting', '0'),
(94, 'eztexting_username', ''),
(95, 'eztexting_password', ''),
(96, 'clickatell_defaultdialingcode', '189'),
(97, 'clickatell_showcodelist', '1'),
(98, 'clickatell_enable_unicode', '0'),
(99, 'sms_new_booking_to_admin', 'New Booking, customer just add new booking with ID {OrderID}'),
(100, 'sms_new_booking_to_admin_checkbox', '0'),
(101, 'sms_new_booking_to_customer', 'You have booked service(s) from {business_name}, your order ID is {OrderID}'),
(102, 'sms_new_booking_to_customer_checkbox', '0'),
(103, 'sms_new_booking_to_employee', ''),
(104, 'sms_new_booking_to_employee_checkbox', '0'),
(105, 'sms_payment_complete_to_admin', 'Payment complete, customer has paid for the order {OrderID}'),
(106, 'sms_payment_complete_to_admin_checkbox', '0'),
(107, 'sms_payment_complete_to_customer', 'You have paid successfully for service(s) from {business_name}, your order ID is {OrderID}'),
(108, 'sms_payment_complete_to_customer_checkbox', '0'),
(109, 'sms_payment_complete_to_employee', ''),
(110, 'sms_payment_complete_to_employee_checkbox', '0'),
(111, 'sms_reminder_notification', 'You have cancelled the booking request. Order ID {OrderID}'),
(112, 'sms_reminder_notification_checkbox', '0'),
(113, 'sms_order_cancelled_notification', 'Booking cancelled, customer has cancelled the order {OrderID}'),
(114, 'sms_order_cancelled_notification_checkbox', '0'),
(115, 'sms_order_cancelled_notification_employee', ''),
(116, 'sms_order_cancelled_notification_employee_checkbox', '0'),
(117, 'order_status_changed_to_customer', ''),
(118, 'order_status_changed_to_customer_checkbox', '0'),
(119, 'show_tax_in_cart', '0'),
(120, 'show_service_cost_including_tax', '0'),
(121, 'disable_calendar_in_off_date', '0'),
(122, 'skip_unavailable_dates', '0'),
(123, 'show_occupied', '1'),
(124, 'use_js_popup', '0'),
(125, 'using_cart', '1'),
(126, 'show_calendar_box', '0'),
(127, 'start_day_in_week', 'sunday'),
(128, 'usingtab', '0'),
(129, 'booking_theme', '0'),
(130, 'show_end_time', '0'),
(131, 'hidetabs', '1'),
(132, 'employee_bar', '1'),
(133, 'employee_phone_email', '1'),
(134, 'employee_information', '1'),
(135, 'show_employee_cost', '1'),
(136, 'show_venue', '1'),
(137, 'show_number_timeslots_booking', '1'),
(138, 'show_dropdown_month_year', '1'),
(139, 'calendar_arrow', 'dark'),
(140, 'header_style', 'btn btn-info'),
(141, 'custom_header_style', ''),
(142, 'calendar_normal_style', 'btn btn-warning'),
(143, 'custom_calendar_normal_style', ''),
(144, 'calendar_activate_style', 'btn btn-info'),
(145, 'custom_calendar_activate_style', ''),
(146, 'calendar_currentdate_style', 'btn btn-danger'),
(147, 'custom_calendar_currentdate_style', ''),
(148, 'calendar_inactivate_style', 'btn btn-inverse'),
(149, 'custom_calendar_inactivate_style', ''),
(150, 'show_service_info_box', '1'),
(151, 'show_service_photo', '1'),
(152, 'show_service_description', '1'),
(153, 'show_booked_information', '1'),
(154, 'show_progress_bar', '1'),
(155, 'progress_bar_background', '#1C67A9'),
(156, 'custom_progress_bar_background', ''),
(157, 'timeslot_background', '#7BA1EB'),
(158, 'custom_timeslot_background', ''),
(159, 'booked_timeslot_background', '#e65789'),
(160, 'custom_booked_timeslot_background', ''),
(161, 'show_details_and_orders', '1'),
(162, 'enable_acymailing', '0'),
(163, 'custom_css', ''),
(164, 'active_privacy', '0'),
(165, 'privacy_policy_article_id', '');