name: Video Carousel
slug: video-carousel
groups: pro
helpId: 5d66105a2c7d3a7a4d77bac4
form:
  general:
    - name : video-carousel-fg_element
      label: Images
      type: group-repeater
      schema:
        - name: author_name
          type: text
          label: Name
          value: John Doe

        - name: author_desig
          type: text
          label: Company & Position
          value: Company & Position

        - name: content
          type: editor
          value: “Lorem Ipsum is simply dummy text of the printing and typesetting industry  has been the industry's standard dummy text ever since the when an unknown printer took a galley.”

        - name: link_type
          label: Video Type
          type: select
          value: link
          options:
            link: Link

        - name: video_link
          label: Video Embed Url
          type: text
          value: https://www.youtube-nocookie.com/embed/xevU2wSGsFs?autoplay=0&amp;showinfo=0&amp;rel=0&amp;modestbranding=1&amp;playsinline=1
          help: add `?controls=0` at the end of youtube embed video link to hide controls
          depends:
            link_type: link

        - name: enable_overlay
          type: switch
          label: Video Overlay
          value: false

        - name: overlay_img
          type: media
          label: Overlay Image
          help: Preview image
          filters: image, unsplash
          showstyle: true
          depends:
            enable_overlay: true

      value:
        - author_name: John Doe
          overlay_img: 'media/quixnxt/images/placeholder.png'
        - author_name: John Doe
          overlay_img: 'media/quixnxt/images/placeholder.png'
        - author_name: John Doe
          overlay_img: 'media/quixnxt/images/placeholder.png'
        - author_name: John Doe
          overlay_img: 'media/quixnxt/images/placeholder.png'
        - author_name: John Doe
          overlay_img: 'media/quixnxt/images/placeholder.png'

    - name    : video-carousel-fg_options
      label   : Columns
      type    : fields-group
      schema  :
        - name : column
          label: Column
          type : select
          value: 3
          options:
            1 : 1
            2 : 2
            3 : 3
            4 : 4
            5 : 5
            6 : 6

    - name    : video-carousel-navigation_style
      label   : Navigation
      type    : fields-group
      schema  :

        - name : show_dot_navigation
          label: Show Dot Navigation
          type : switch
          value: true

        - name: bar_navigation
          label: Enable Bar Nav
          type: switch
          value: false

        - name: bar_vertical
          label: For Vertical
          type: switch
          value: false
          depends:
            bar_navigation: true

        - name : barNav_position
          label: Position
          type : select
          value: 'bottom-center'
          options:
            'top-left' : 'Top Left'
            'top-right' : 'Top Right'
            'center-left' : 'Center Left'
            'center-right' : 'Center Right'
            'bottom-left' : 'Bottom Left'
            'bottom-center' : 'Bottom Center'
            'bottom-right' : 'Bottom Right'
          depends:
            bar_navigation: true

        - name : barNav_margin
          label: Margin
          type : select
          value: 'medium'
          options:
            'none' : 'None'
            'small' : 'Small'
            'medium' : 'Medium'
            'large' : 'Large'
          depends:
            bar_navigation: true

    - name    : video_carousel-fg_behaviour
      label   : Behaviour
      type    : fields-group
      schema  :
        - name: play_icon
          lable: Play Icon
          type: switch
          value: false
          help: Enbale the overlay image at first

        - name: upload_Picon
          type: media
          label: Upload Icon
          showstyle: true
          value: media/quixnxt/images/placeholder.png
          depends:
            play_icon: true

        - name: pause_on_hover
          label: Pause on Hover
          type: switch
          value: true

        - name : auto_play
          label: Auto Play
          type : switch
          value: true

        - name: autoplay_speed
          label: Autoplay Speed ( MS )
          type: text
          value: 5000
          depends:
            auto_play: true

        - name: infinite_loop
          label: Infinite Loop
          type: switch
          value: false

        - name : set
          label: Slide as a Set
          type : switch
          value: false

  styles:
    - name    : video-carousel-fg_style
      label   : Video
      type    : fields-group
      status  : open
      schema  :
        - name : height
          type : slider
          defaultUnit: px
          max: 1000
          value:
            desktop : 200
            tablet : 100
            phone : 100

        - name : width
          type : slider
          defaultUnit: %
          max: 1000
          value:
            desktop : 100
            tablet : 100
            phone : 100

    - name    : video-title-fg_style
      label   : Name
      type    : fields-group
      schema  :
        - name: title_color
          label: Color
          type: color
          value: rgba(0, 0, 0, 1)

        - name: title_font
          label: Typography
          type: typography
          popover: true

    - name    : video-des-comp-fg_style
      label   : Company & Position
      type    : fields-group
      schema  :
        - name: desig_color
          label: Color
          type: color
          value: rgba(0, 0, 0, 1)

        - name: desig_font
          label: Typography
          type: typography
          popover: true

    - name    : video-content-fg_style
      label   : Content
      type    : fields-group
      schema  :
        - name  : content_padding
          label : Padding
          type: dimensions
          units: px
          defaultUnit: px

        - name: content_color
          label: Color
          type: color
          value: rgba(0, 0, 0, 1)

        - name: content_font
          label: Typography
          type: typography
          popover: true

    - name    : dot-fg_style
      label   : Dot Navigation
      type    : fields-group
      schema  :
        - name: dot_color
          label: Dot Color
          type: color
          value: rgba(238, 238, 238, 1)

        - name: dot_active_color
          label: Dot Active Color
          type: color
          value: rgba(102, 102, 102, 0.6)

        - name  : dot_width
          label : Dot Width
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 15
            tablet : 15
            phone : 15

        - name  : dot_spacing
          label : Dot Spacing
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 12
            tablet : 12
            phone : 10

        - name  : dot_margin
          label : Dot Margin
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 25
            tablet : 25
            phone : 20

    - name    : video_carousel_fg_bar-style
      label   : Bar Navigation
      type    : fields-group
      status  : close
      schema  :
        - name: bar_color
          label: Bar Color
          type: color
          value: rgba(238, 238, 238, 1)

        - name: bar_active_color
          label: Bar Active Color
          type: color
          value: rgba(102, 102, 102, 0.6)

        - name  : bar_width
          label : Bar Width
          type: slider
          max : 100
          units: px
          help: Height for Vartical bar
          defaultUnit: px
          value:
            desktop : 25
            tablet : 25
            phone : 25

        - name  : barActive_width
          label : Bar Active Width
          type: slider
          max : 100
          units: px
          help: Width (Active) for Vartical bar
          defaultUnit: px

        - name  : bar_height
          label : Bar Height
          type: slider
          max : 100
          units: px
          help: Width for Vartical bar
          defaultUnit: px
          value:
            desktop : 5
            tablet : 5
            phone : 5

        - name  : barActive_height
          label : Bar Active Height
          type: slider
          max : 100
          units: px
          help: Height (Active) for Vartical bar
          defaultUnit: px
