<?php
// namespace administrator\components\com_jmap\libraries\framework\composer;
/**
 *
 * @package JMAP::administrator::components::com_jmap
 * @subpackage framework
 * @subpackage composer
 * @author Joomla! Extensions Store
 * @copyright (C) 2021 - Joomla! Extensions Store
 * @license GNU/GPLv2 http://www.gnu.org/licenses/gpl-2.0.html
 */
defined ( '_JEXEC' ) or die ( 'Restricted access' );

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__)) . '/Google';
$baseDir = dirname($vendorDir);

return array(
);
