<?php
// namespace administrator\components\com_jmap\libraries\framework\composer;
/**
 *
 * @package JMAP::administrator::components::com_jmap
 * @subpackage framework
 * @subpackage composer
 * @author Joomla! Extensions Store
 * @copyright (C) 2021 - Joomla! Extensions Store
 * @license GNU/GPLv2 http://www.gnu.org/licenses/gpl-2.0.html
 */
defined ( '_JEXEC' ) or die ( 'Restricted access' );

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitcb4c0ac1dedbbba2f0b42e9cdf4d93d7
{
    private static $loader;

    public static function loadClassLoader($class)
    {
		if ('Composer\Autoload\JMap\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitcb4c0ac1dedbbba2f0b42e9cdf4d93d7', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\JMap\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInitcb4c0ac1dedbbba2f0b42e9cdf4d93d7', 'loadClassLoader'));

        $useStaticLoader = false;
        if ($useStaticLoader) {
            require __DIR__ . '/autoload_static.php';

            call_user_func(\Composer\Autoload\ComposerStaticInitcb4c0ac1dedbbba2f0b42e9cdf4d93d7::getInitializer($loader));
        } else {
            $map = require __DIR__ . '/autoload_namespaces.php';
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . '/autoload_psr4.php';
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        if ($useStaticLoader) {
            $includeFiles = Composer\Autoload\ComposerStaticInitcb4c0ac1dedbbba2f0b42e9cdf4d93d7::$files;
        } else {
            $includeFiles = require __DIR__ . '/autoload_files.php';
        }
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequirecb4c0ac1dedbbba2f0b42e9cdf4d93d7($fileIdentifier, $file);
        }

        return $loader;
    }
}

function composerRequirecb4c0ac1dedbbba2f0b42e9cdf4d93d7($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}
