INSERT INTO `#__osmembership_mitems` (`id`, `name`, `title`, `title_en`, `type`, `group`, `translatable`, `featured`) VALUES
(1, 'admin_email_subject', 'OSM_ADMIN_EMAIL_SUBJECT', 'Admin Email Subject', 'text', 1, 1, 0),
(2, 'admin_email_body', 'OSM_ADMIN_EMAIL_BODY', 'Admin Email Body', 'editor', 1, 1, 0),
(3, 'user_email_subject', 'OSM_USER_EMAIL_SUBJECT', 'User Email Subject', 'text', 1, 1, 0),
(4, 'user_email_body', 'OSM_USER_EMAIL_BODY', 'User Email Body', 'editor', 1, 1, 0),
(5, 'user_email_body_offline', 'OSM_USER_EMAIL_BODY_OFFLINE_PAYMENT', 'User Email Body (Offline Payment)', 'editor', 1, 1, 0),
(6, 'subscription_approved_email_subject', 'OSM_SUBSCRIPTION_APPROVED_EMAIL_SUBJECT', 'Subscription Approved Subject', 'text', 1, 1, 0),
(7, 'subscription_approved_email_body', 'OSM_SUBSCRIPTION_APPROVED_EMAIL_BODY', 'Subscription Approved Body', 'editor', 1, 1, 0),
(8, 'admin_subscription_approved_email_subject', 'OSM_ADMIN_SUBSCRIPTION_APPROVED_EMAIL_SUBJECT', 'Admin Subscription Approved Subject', 'text', 1, 1, 0),
(9, 'admin_subscription_approved_email_body', 'OSM_ADMIN_SUBSCRIPTION_APPROVED_EMAIL_BODY', 'Admin Subscription Approved Body', 'editor', 1, 1, 0),
(10, 'subscription_form_msg', 'OSM_SUBSCRIPTION_FORM_MESSAGE', 'Subscription Form Message', 'editor', 1, 1, 0),
(11, 'thanks_message', 'OSM_THANK_MESSAGE', 'Thank You Message', 'editor', 1, 1, 0),
(12, 'thanks_message_offline', 'OSM_THANK_MESSAGE_OFFLINE', 'Thank You Message (Offline Payment)', 'editor', 1, 1, 0),
(13, 'cancel_message', 'OSM_PAYMENT_CANCEL_MESSAGE', 'Payment Cancel Message', 'editor', 1, 1, 0),
(14, 'failure_message', 'OSM_PAYMENT_FAILURE_MESSAGE', 'Payment Failure Message', 'editor', 1, 1, 0),
(15, 'profile_update_email_subject', 'OSM_PROFILE_UPDATE_EMAIL_SUBJECT', 'Profile Update Email Subject', 'text', 1, 1, 0),
(16, 'profile_update_email_body', 'OSM_PROFILE_UPDATE_EMAIL_BODY', 'Profile Update Email Body', 'editor', 1, 1, 0),
(17, 'content_restricted_message', 'OSM_CONTENT_RESTRICTED_MESSAGE', 'Content Restricted Message', 'editor', 1, 1, 0),
(18, 'mass_mail_template', 'OSM_MASS_MAIL_TEMPLATE', 'Mass Mail Template', 'editor', 1, 0, 0),
(19, 'subscription_renew_form_msg', 'OSM_SUBSCRIPTION_RENEW_FORM_MESSAGE', 'Subscription Renew Form Message', 'editor', 2, 1, 0),
(20, 'admin_renw_email_subject', 'OSM_RENEW_ADMIN_EMAIL_SUBJECT', 'Subscription Renewal Admin Email Subject', 'text', 2, 1, 0),
(21, 'admin_renew_email_body', 'OSM_RENEW_ADMIN_EMAIL_BODY', 'Subscription Renewal Admin Email Body', 'editor', 2, 1, 0),
(22, 'user_renew_email_subject', 'OSM_RENEW_USER_EMAIL_SUBJECT', 'Subscription Renewal User Email Subject', 'text', 2, 1, 0),
(23, 'user_renew_email_body', 'OSM_RENEW_USER_EMAIL_BODY', 'Subscription Renewal User Email Body', 'editor', 2, 1, 0),
(24, 'user_renew_email_body_offline', 'OSM_RENEW_USER_EMAIL_BODY_OFFLINE', 'Subscription Renewal User Email Body (Offline Payment)', 'editor', 2, 1, 0),
(25, 'renew_thanks_message', 'OSM_RENEW_THANK_MESSAGE', 'Subscription Renewal Thanks Message', 'editor', 2, 1, 0),
(26, 'renew_thanks_message_offline', 'OSM_RENEW_THANK_MESSAGE_OFFLINE', 'Subscription Renewal Thanks Message (Offline Payment)', 'editor', 2, 1, 0),
(27, 'subscription_upgrade_form_msg', 'OSM_SUBSCRIPTION_UPGRADE_FORM_MESSAGE', 'Subscription Upgrade Form Message', 'editor', 3, 1, 0),
(28, 'admin_upgrade_email_subject', 'OSM_UPGRADE_ADMIN_EMAIL_SUBJECT', 'Subscription Upgrade Admin Email Subject', 'text', 3, 1, 0),
(29, 'admin_upgrade_email_body', 'OSM_UPGRADE_ADMIN_EMAIL_BODY', 'Subscription Upgrade Admin Email Body', 'editor', 3, 1, 0),
(30, 'user_upgrade_email_subject', 'OSM_UPGRADE_USER_EMAIL_SUBJECT', 'Subscription Upgrade User Email Subject', 'text', 3, 1, 0),
(31, 'user_upgrade_email_body', 'OSM_UPGRADE_USER_EMAIL_BODY', 'Subscription Upgrade User Email Body', 'editor', 3, 1, 0),
(32, 'user_upgrade_email_body_offline', 'OSM_UPGRADE_USER_EMAIL_BODY_OFFLINE', 'Subscription upgrade user email body (Offline Payment)', 'editor', 3, 1, 0),
(33, 'upgrade_thanks_message', 'OSM_UPGRADE_THANK_MESSAGE', 'Subscription Upgrade Thanks Message', 'editor', 3, 1, 0),
(34, 'upgrade_thanks_message_offline', 'OSM_UPGRADE_THANK_MESSAGE_OFFLINE', 'Subscription Upgrade Thanks Message (Offline Payment)', 'editor', 3, 1, 0),
(35, 'recurring_subscription_cancel_message', 'OSM_RECURRING_SUBSCRIPTION_CANCEL_MESSAGE', 'Recurring Subscription Cancel Message', 'editor', 4, 1, 0),
(36, 'user_recurring_subscription_cancel_subject', 'OSM_USER_RECURRING_SUBSCRIPTION_CANCEL_EMAIL_SUBJECT', 'User Recurring Subscription Cancel Email Subject', 'text', 4, 1, 0),
(37, 'user_recurring_subscription_cancel_body', 'OSM_USER_RECURRING_SUBSCRIPTION_CANCEL_EMAIL_BODY', 'User Recurring Subscription Cancel Email Body', 'editor', 4, 1, 0),
(38, 'admin_recurring_subscription_cancel_subject', 'OSM_ADMIN_RECURRING_SUBSCRIPTION_CANCEL_EMAIL_SUBJECT', 'Admin Recurring Subscription Cancel Email Subject', 'text', 4, 1, 0),
(39, 'admin_recurring_subscription_cancel_body', 'OSM_ADMIN_RECURRING_SUBSCRIPTION_CANCEL_EMAIL_BODY', 'Admin Recurring Subscription Cancel Email Body', 'editor', 4, 1, 0),
(40, 'offline_recurring_email_subject', 'OSM_OFFLINE_RECURRING_RENEWAL_EMAIL_SUBJECT', 'Offline Recurring Email Subject', 'text', 4, 1, 0),
(41, 'offline_recurring_email_body', 'OSM_OFFLINE_RECURRING_RENEWAL_EMAIL_BODY', 'Offline Recurring Email Body', 'editor', 4, 1, 0),
(42, 'first_reminder_email_subject', 'OSM_FIRST_REMINDER_EMAIL_SUBJECT', 'First Reminder Email Subject', 'text', 5, 1, 0),
(43, 'first_reminder_email_body', 'OSM_FIRST_REMINDER_EMAIL_BODY', 'First Reminder Email Body', 'editor', 5, 1, 0),
(44, 'second_reminder_email_subject', 'OSM_SECOND_REMINDER_EMAIL_SUBJECT', 'Second Reminder Email Subject', 'text', 5, 1, 0),
(45, 'second_reminder_email_body', 'OSM_SECOND_REMINDER_EMAIL_BODY', 'Second Reminder Email Body', 'editor', 5, 1, 0),
(46, 'third_reminder_email_subject', 'OSM_THIRD_REMINDER_EMAIL_SUBJECT', 'Third Reminder Email Subject', 'text', 5, 1, 0),
(47, 'third_reminder_email_body', 'OSM_THIRD_REMINDER_EMAIL_BODY', 'Third Reminder Email Body', 'editor', 5, 1, 0),
(48, 'subscription_end_email_subject', 'OSM_SUBSCRIPTION_END_EMAIL_SUBJECT', 'Recurring Subscription End Email Subject', 'text', 5, 1, 0),
(49, 'subscription_end_email_body', 'OSM_SUBSCRIPTION_END_EMAIL_BODY', 'Recurring Subscription End Email Body', 'editor', 5, 1, 0),
(50, 'new_group_member_email_subject', 'OSM_NEW_GROUP_MEMBER_EMAIL_SUBJECT', 'New Group Member Email Subject', 'text', 6, 1, 0),
(51, 'new_group_member_email_body', 'OSM_NEW_GROUP_MEMBER_EMAIL_BODY', 'New Group Member Email Body', 'editor', 6, 1, 0),
(52, 'join_group_form_message', 'OSM_JOIN_GROUP_FROM_MESSAGE', 'Join Group Form Message', 'editor', 6, 1, 0),
(53, 'join_group_complete_message', 'OSM_JOIN_GROUP_COMPLETE_MESSAGE', 'Join Group Complete Message', 'editor', 6, 1, 0),
(54, 'join_group_user_email_subject', 'OSM_JOIN_GROUP_USER_EMAIL_SUBJECT', 'Join Group User Email Subject', 'text', 6, 1, 0),
(55, 'join_group_user_email_body', 'OSM_JOIN_GROUP_USER_EMAIL_BODY', 'Body of email sent to users when they join a group', 'editor', 6, 1, 0),
(56, 'join_group_group_admin_email_subject', 'OSM_JOIN_GROUP_GROUP_ADMIN_EMAIL_SUBJECT', 'Join Group Group Admin Email Subject', 'text', 6, 1, 0),
(57, 'join_group_group_admin_email_body', 'OSM_JOIN_GROUP_GROUP_ADMIN_EMAIL_BODY', 'Join Group Group Admin Email Body', 'editor', 6, 1, 0),
(58, 'subscription_payment_form_message', 'OSM_SUBSCRIPTION_PAYMENT_FORM_MESSAGE', 'Subscription Payment Form Message', 'editor', 7, 1, 0),
(59, 'subscription_payment_admin_email_subject', 'OSM_SUBSCRIPTION_PAYMENT_ADMIN_EMAIL_SUBJECT', 'Subscription Payment Admin Email Subject', 'text', 7, 1, 0),
(60, 'subscription_payment_admin_email_body', 'OSM_SUBSCRIPTION_PAYMENT_ADMIN_EMAIL_BODY', 'Subscription Payment Admin Email Body', 'editor', 7, 1, 0),
(61, 'subscription_payment_user_email_subject', 'OSM_SUBSCRIPTION_PAYMENT_USER_EMAIL_SUBJECT', 'Subscription Payment User Email Subject', 'text', 7, 1, 0),
(62, 'subscription_payment_user_email_body', 'OSM_SUBSCRIPTION_PAYMENT_USER_EMAIL_BODY', 'Subscription Payment User Email Body', 'editor', 7, 1, 0),
(63, 'subscription_payment_thanks_message', 'OSM_SUBSCRIPTION_PAYMENT_THANK_MESSAGE', 'Subscription Payment Thank You Message', 'editor', 7, 1, 0),
(64, 'request_payment_email_subject', 'OSM_REQUEST_PAYMENT_EMAIL_SUBJECT', 'Request Payment Email Subject', 'text', 7, 1, 0),
(65, 'request_payment_email_body', 'OSM_REQUEST_PAYMENT_EMAIL_BODY', 'Request Payment Email Body', 'editor', 7, 1, 0),
(66, 'new_subscription_admin_sms', 'OSM_NEW_SUBSCRIPTION_ADMIN_SMS', 'New Subscription SMS', 'textarea', 8, 0, 0),
(67, 'new_subscription_renewal_admin_sms', 'OSM_NEW_SUBSCRIPTION_RENEWAL_ADMIN_SMS', 'New Subscription Renewal SMS', 'textarea', 8, 0, 0),
(68, 'new_subscription_upgrade_admin_sms', 'OSM_NEW_SUBSCRIPTION_UPGRADE_ADMIN_SMS', 'New Subscription Upgrade SMS', 'textarea', 8, 0, 0),
(69, 'first_reminder_sms', 'OSM_FIRST_REMINDER_SMS', 'First Reminder SMS', 'textarea', 8, 0, 0),
(70, 'second_reminder_sms', 'OSM_SECOND_REMINDER_SMS', 'Second Reminder SMS', 'textarea', 8, 0, 0),
(71, 'third_reminder_sms', 'OSM_THIRD_REMINDER_SMS', 'Third Reminder SMS', 'textarea', 8, 0, 0);