name: Social Icon
slug: social-icon
groups: general
helpId: 5d1ff0772c7d3a5cd38ec1d6
form:
  general:
    - name: social_list
      type: group-repeater
      schema:

        - name: title
          type: text
          value: Icon

        - name: link
          type: link
          value:
            url : '#'
            target: ''
            nofollow: ''

        - name: icon
          type: media
          filters: icon
          showstyle: true

      value:
        - title: Facebook
          icon: 'media/quixnxt/images/placeholder.png'

        - title: Twitter
          icon: 'media/quixnxt/images/placeholder.png'

        - title: LinkedIn
          icon: 'media/quixnxt/images/placeholder.png'

    - name: basic_setting
      label: Basic
      type: fields-group
      status: close
      schema:
        - name: choose_layout
          label: Layout
          type: choose
          value:
            desktop: horizontal
            tablet: horizontal
            phone: horizontal
          options:
            vertical:
              label: Vertical
            horizontal:
              label: Horizontal

        - name: alignment
          type: choose
          label: Position
          responsive: true
          value:
            desktop: left
            tablet: left
            phone: left
          options:
            left:
              label: Left
              icon: qxuicon-align-left
            center:
              label: Center
              icon: qxuicon-align-center
            right:
              label: Right
              icon: qxuicon-align-right

  styles:
    - name: spacing_setting
      label: Common
      type: fields-group
      status: close
      schema:
        - name: item_spacing
          label: Item Spacing
          type: slider
          units: px
          defaultUnit: px
          max: 100
          value:
            desktop: 5
            tablet: 5
            phone: 5

        - name: item_padding
          label: Item Padding
          type: dimensions
          units: px
          defaultUnit: px

        - name: btn_border
          label: Border
          type: border
          popover: true

    - name: color_setting
      label: Color
      type: fields-group
      status: close
      schema:
        - name: icon_hover
          label: Icon Hover Color
          type: color

        - name: icon_bg
          label: Background
          type: color

        - name: icon_hover_bg
          label: Background Hover Color
          type: color
