INSERT INTO `#__eb_mitems` (`id`, `name`, `title`, `description`, `type`, `group`, `translatable`, `featured`, `title_en`) VALUES
(1, 'intro_text', 'EB_INTRO_TEXT', 'EB_INTRO_TEXT_EXPLAIN', 'editor', '1', 1, 0, 'Intro Text'),
(2, 'registration_form_message', 'EB_REGISTRATION_FORM_MESSAGE', 'EB_REGISTRATION_FORM_MESSAGE_EXPLAIN', 'editor', '1', 1, 0, 'Registration Form Message (Individual)'),
(3, 'registration_form_message_group', 'EB_REGISTRATION_FORM_MESSAGE_GROUP', 'EB_REGISTRATION_FORM_MESSAGE_GROUP_EXPLAIN', 'editor', '1', 1, 0, 'Registration Form Message (Group)'),
(4, 'number_members_form_message', 'EB_NUMBER_OF_MEMBERS_FORM_MESSAGE', 'EB_NUMBER_OF_MEMBERS_FORM_MESSAGE_EXPLAIN', 'editor', '1', 1, 0, 'Number Of Members Form Message'),
(5, 'member_information_form_message', 'EB_MEMBER_INFORMATION_FORM_MESSAGE', 'EB_MEMBER_INFORMATION_FORM_MESSAGE_EXPLAIN', 'editor', '1', 1, 0, 'Member Information Form Message'),
(6, 'thanks_message', 'EB_THANK_YOU_MESSAGE', 'EB_THANK_YOU_MESSAGE_EXPLAIN', 'editor', '1', 1, 0, 'Thank You Message'),
(7, 'thanks_message_offline', 'EB_THANK_YOU_MESSAGE_OFFLINE', 'EB_THANK_YOU_MESSAGE_OFFLINE_EXPLAIN', 'editor', '1', 1, 0, 'Thank You Message (Offline)'),
(8, 'cancel_message', 'EB_CANCEL_MESSAGE', 'EB_CANCEL_MESSAGE_EXPLAIN', 'editor', '1', 1, 0, 'Cancel Message'),
(9, 'submit_event_form_message', 'EB_SUBMIT_EVENT_FORM_MESSAGE', 'EB_SUBMIT_EVENT_FORM_MESSAGE_EXPLAIN', 'editor', '1', 1, 0, 'Submit Event Form Message'),
(10, 'mass_mail_template', 'EB_MASS_MAIL_TEMPLATE', 'EB_MASS_MAIL_TEMPLATE_EXPLAIN', 'editor', '1', 1, 0, 'Mass Mail Template'),
(11, 'admin_email_subject', 'EB_ADMIN_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'Admin Email Subject'),
(12, 'admin_email_body', 'EB_ADMIN_EMAIL_BODY', '', 'editor', '2', 1, 0, 'Admin Email Body'),
(13, 'user_email_subject', 'EB_USER_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'User Email Subject'),
(14, 'user_email_body', 'EB_USER_EMAIL_BODY', '', 'editor', '2', 1, 0, 'User Email Body'),
(15, 'user_email_body_offline', 'EB_USER_EMAIL_BODY_OFFLINE', '', 'editor', '2', 1, 0, 'User Email Body (Offline Payment)'),
(16, 'group_member_email_subject', 'EB_GROUP_MEMBER_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'Group Member Email Subject'),
(17, 'group_member_email_body', 'EB_GROUP_MEMBER_EMAIL_BODY', '', 'editor', '2', 1, 0, 'Group Member Email Body'),
(18, 'registration_approved_email_subject', 'EB_REGISTRATION_APPROVED_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'Registration Approved Email Subject'),
(19, 'registration_approved_email_body', 'EB_REGISTRATION_APPROVED_EMAIL_BODY', '', 'editor', '2', 1, 0, 'Registration Approved Email Body'),
(20, 'admin_registration_approved_email_subject', 'EB_ADMIN_REGISTRATION_APPROVED_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'Admin Registration Approved Email Subject'),
(21, 'admin_registration_approved_email_body', 'EB_ADMIN_REGISTRATION_APPROVED_EMAIL_BODY', '', 'editor', '2', 1, 0, 'Admin Registration Approved Email Body'),
(22, 'certificate_email_subject', 'EB_CERTIFICATE_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'Certificate Email Subject'),
(23, 'certificate_email_body', 'EB_CERTIFICATE_EMAIL_BODY', 'EB_CERTIFICATE_EMAIL_BODY_EXPLAIN', 'editor', '2', 1, 0, 'Certificate Email Body'),
(24, 'event_cancel_email_subject', 'EB_EVENT_CANCEL_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'Event Cancel Email Subject'),
(25, 'event_cancel_email_body', 'EB_CANCEL_EMAIL_BODY', 'EB_CANCEL_EMAIL_BODY_EXPLAIN', 'editor', '2', 1, 0, 'Event Cancel Email Body'),
(26, 'send_registrants_list_email_subject', 'EB_SEND_REGISTRANTS_LIST_EMAIL_SUBJECT', '', 'text', '2', 1, 0, 'Send Registrants List Email Subject'),
(27, 'send_registrants_list_email_body', 'EB_SEND_REGISTRANTS_LIST_EMAIL_BODY', 'EB_SEND_REGISTRANTS_LIST_EMAIL_BODY_EXPLAIN', 'editor', '2', 1, 0, 'Send Registrants List Email Body'),
(28, 'reminder_email_subject', 'EB_REMINDER_EMAIL_SUBJECT', '', 'text', '3', 1, 0, 'First Reminder Email Subject'),
(29, 'reminder_email_body', 'EB_REMINDER_EMAIL_BODY', '', 'editor', '3', 1, 0, 'First Reminder Email Body'),
(30, 'second_reminder_email_subject', 'EB_SECOND_REMINDER_EMAIL_SUBJECT', '', 'text', '3', 1, 0, 'Second Reminder Email Subject'),
(31, 'second_reminder_email_body', 'EB_SECOND_REMINDER_EMAIL_BODY', '', 'editor', '3', 1, 0, 'Second Reminder Email Body'),
(32, 'third_reminder_email_subject', 'EB_THIRD_REMINDER_EMAIL_SUBJECT', '', 'text', '3', 1, 0, 'Third Reminder Email Subject'),
(33, 'third_reminder_email_body', 'EB_THIRD_REMINDER_EMAIL_BODY', '', 'editor', '3', 1, 0, 'Third Reminder Email Body'),
(34, 'offline_payment_reminder_email_subject', 'EB_OFFLINE_PAYMENT_REMINDER_EMAIL_SUBJECT', '', 'text', '3', 1, 0, 'Offline Payment Reminder Email Subject'),
(35, 'offline_payment_reminder_email_body', 'EB_OFFLINE_PAYMENT_REMINDER_EMAIL_BODY', '', 'editor', '3', 1, 0, 'Offline Payment Reminder Email Body'),
(36, 'registration_cancel_confirmation_message', 'EB_REGISTRATION_CANCEL_CONFIRMATION_MESSAGE', '', 'editor', '4', 1, 0, 'Registration Cancel Confirmation Message'),
(37, 'registration_cancel_message_free', 'EB_REGISTRATION_CANCEL_MESSAGE_FREE', 'EB_REGISTRATION_CANCEL_MESSAGE_FREE_EXPLAIN', 'editor', '4', 1, 0, 'Registration Cancel Message (Free Event)'),
(38, 'registration_cancel_message_paid', 'EB_REGISTRATION_CANCEL_MESSAGE_PAID', 'EB_REGISTRATION_CANCEL_MESSAGE_PAID_EXPLAIN', 'editor', '4', 1, 0, 'Registration Cancel Message (Paid Event)'),
(39, 'registration_cancel_confirmation_email_subject', 'EB_REGISTRATION_CANCEL_CONFIRMATION_EMAIL_SUBJECT', '', 'text', '4', 1, 0, 'Registration Cancel Confirmation Email Subject'),
(40, 'registration_cancel_confirmation_email_body', 'EB_REGISTRATION_CANCEL_CONFIRMATION_EMAIL_BODY', '', 'editor', '4', 1, 0, 'Registration Cancel Confirmation Email Body'),
(41, 'registration_cancel_email_subject', 'EB_CANCEL_NOTIFICATION_EMAIL_SUBJECT', '', 'text', '4', 1, 0, 'Registration Cancel Notification Email Subject'),
(42, 'registration_cancel_email_body', 'EB_CANCEL_NOTIFICATION_EMAIL_BODY', '', 'editor', '4', 1, 0, 'Registration Cancel Notification Email Body'),
(43, 'user_registration_cancel_subject', 'EB_USER_REGISTRATION_CANCEL_SUBJECT', '', 'text', '4', 1, 0, 'User Registration Cancelled Email Subject'),
(44, 'user_registration_cancel_message', 'EB_USER_REGISTRATION_CANCEL_MESSAGE', 'EB_USER_REGISTRATION_CANCEL_MESSAGE_EXPLAIN', 'editor', '4', 1, 0, 'User Registration Cancelled Email Message'),
(45, 'submit_event_user_email_subject', 'EB_SUBMIT_EVENT_USER_EMAIL_SUBJECT', '', 'text', '5', 1, 0, 'User Email Subject'),
(46, 'submit_event_user_email_body', 'EB_SUBMIT_EVENT_USER_EMAIL_BODY', '', 'editor', '5', 1, 0, 'User Email Body'),
(47, 'submit_event_admin_email_subject', 'EB_SUBMIT_EVENT_ADMIN_EMAIL_SUBJECT', '', 'text', '5', 1, 0, 'Admin Email Subject'),
(48, 'submit_event_admin_email_body', 'EB_SUBMIT_EVENT_ADMIN_EMAIL_BODY', '', 'editor', '5', 1, 0, 'Admin Email Body'),
(49, 'event_approved_email_subject', 'EB_EVENT_APPROVED_EMAIL_SUBJECT', '', 'text', '5', 1, 0, 'Event Approved Email Subject'),
(50, 'event_approved_email_body', 'EB_EVENT_APPROVED_EMAIL_BODY', '', 'editor', '5', 1, 0, 'Event Approved Email Body'),
(51, 'event_update_email_subject', 'EB_EVENT_UPDATE_EMAIL_SUBJECT', '', 'text', '5', 1, 0, 'Event Update Email Subject'),
(52, 'event_update_email_body', 'EB_EVENT_UPDATE_EMAIL_BODY', '', 'editor', '5', 1, 0, 'Event Update Email Body'),
(53, 'invitation_form_message', 'EB_INVITATION_FORM_MESSAGE', 'EB_INVITATION_FORM_MESSAGE_EXPLAIN', 'editor', '6', 1, 0, 'Invitation Form Message'),
(54, 'invitation_complete', 'EB_INVITATION_COMPLETE_MESSAGE', 'EB_INVITATION_COMPLETE_MESSAGE_EXPLAIN', 'editor', '6', 1, 0, 'Invitation Complete Message'),
(55, 'invitation_email_subject', 'EB_INVITATION_EMAIL_SUBJECT', '', 'text', '6', 1, 0, 'Invitation Email subject'),
(56, 'invitation_email_body', 'EB_INVITATION_EMAIL_BODY', '', 'editor', '6', 1, 0, 'Invitation Email Body'),
(57, 'waitinglist_form_message', 'EB_WAITING_LIST_FORM_MESSAGE', 'EB_WAITING_LIST_FORM_MESSAGE_EXPLAIN', 'editor', '7', 1, 0, 'Waiting List Form Message'),
(58, 'waitinglist_complete_message', 'EB_WAITING_LIST_COMPLETE_MESSAGE', 'EB_WAITING_LIST_COMPLETE_MESSAGE_EXPLAIN', 'editor', '7', 1, 0, 'Waiting List Complete Message'),
(59, 'watinglist_confirmation_subject', 'EB_WAITING_LIST_CONFIRMATION_SUBJECT', 'EB_WAITING_LIST_CONFIRMATION_SUBJECT_EXPLAIN', 'text', '7', 1, 0, 'Waiting List Confirmation Email Subject'),
(60, 'watinglist_confirmation_body', 'EB_WAITING_LIST_CONFIRMATION_BODY', 'EB_WAITING_LIST_COMPLETE_MESSAGE_EXPLAIN', 'editor', '7', 1, 0, 'Waiting List Confirmation Email Body'),
(61, 'watinglist_notification_subject', 'EB_WAITING_LIST_NOTIFICATION_SUBJECT', 'EB_WAITING_LIST_NOTIFICATION_SUBJECT_EXPLAIN', 'text', '7', 1, 0, 'Waiting List Notification Email Subject'),
(62, 'watinglist_notification_body', 'EB_WAITING_LIST_NOTIFICATION_BODY', 'EB_WAITING_LIST_NOTIFICATION_BODY_EXPLAIN', 'editor', '7', 1, 0, 'Waiting List Notification Email Body'),
(63, 'registrant_waitinglist_notification_subject', 'EB_REGISTRANT_WAITING_LIST_NOTIFICATION_SUBJECT', 'EB_REGISTRANT_WAITING_LIST_NOTIFICATION_SUBJECT_EXPLAIN', 'text', '7', 1, 0, 'Registrant Waiting List Notification Email Subject'),
(64, 'registrant_waitinglist_notification_body', 'EB_REGISTRANT_WAITING_LIST_NOTIFICATION_BODY', 'EB_REGISTRANT_WAITING_LIST_NOTIFICATION_BODY_EXPLAIN', 'editor', '7', 1, 0, 'Registrant Waiting List Notification Email Body'),
(65, 'request_payment_email_subject', 'EB_REQUEST_PAYMENT_EMAIL_SUBJECT', 'EB_REQUEST_PAYMENT_EMAIL_SUBJECT_EXPLAIN', 'text', '7', 1, 0, 'Payment Request Email Subject'),
(66, 'request_payment_email_body', 'EB_REQUEST_PAYMENT_EMAIL_BODY', 'EB_REQUEST_PAYMENT_EMAIL_BODY_EXPLAIN', 'editor', '7', 1, 0, 'Request Payment Email Body'),
(67, 'request_payment_email_subject_pdr', 'EB_REQUEST_PAYMENT_EMAIL_SUBJECT_FOR_PENDING_REGISTRATION', 'EB_REQUEST_PAYMENT_EMAIL_SUBJECT_FOR_PENDING_REGISTRATION_EXPLAIN', 'text', '7', 1, 0, 'Payment Request Email Subject For Pending Registration'),
(68, 'request_payment_email_body_pdr', 'EB_REQUEST_PAYMENT_EMAIL_BODY_FOR_PENDING_REGISTRATION', 'EB_REQUEST_PAYMENT_EMAIL_BODY_FOR_PENDING_REGISTRATION_EXPLAIN', 'editor', '7', 1, 0, 'Request Payment Email Body For Pending Registration'),
(69, 'registration_payment_form_message', 'EB_REGISTRATION_PAYMENT_FORM_MESSAGE', 'EB_REGISTRATION_PAYMENT_FORM_MESSAGE_EXPLAIN', 'editor', '7', 1, 0, 'Registration Payment Form Message'),
(70, 'waiting_list_cancel_confirmation_message', 'EB_WAITING_LIST_CANCEL_CONFIRMATION_MESSAGE', 'EB_WAITING_LIST_CANCEL_CONFIRMATION_MESSAGE_EXPLAIN', 'editor', '7', 1, 0, 'Waiting List Cancel Confirmation Message'),
(71, 'waiting_list_cancel_complete_message', 'EB_WAITING_LIST_CANCEL_COMPLETE_MESSAGE', 'EB_WAITING_LIST_CANCEL_COMPLETE_MESSAGE_EXPLAIN', 'editor', '7', 1, 0, 'Waiting List Cancel Complete Message'),
(72, 'waiting_list_cancel_confirmation_email_subject', 'EB_WAITING_LIST_CANCEL_CONFIRMATION_EMAIL_SUBJECT', '', 'text', '7', 1, 0, 'Waiting List Cancel Confirmation Email Subject'),
(73, 'waiting_list_cancel_confirmation_email_body', 'EB_WAITING_LIST_CANCEL_CONFIRMATION_EMAIL_BODY', '', 'editor', '7', 1, 0, 'Waiting List Cancel Confirmation Email Body'),
(74, 'waiting_list_cancel_notification_email_subject', 'EB_WAITING_LIST_CANCEL_NOTIFICATION_EMAIL_SUBJECT', '', 'text', '7', 1, 0, 'Waiting List Cancel Notification Email Subject'),
(75, 'waiting_list_cancel_notification_email_body', 'EB_WAITING_LIST_CANCEL_NOTIFICATION_EMAIL_BODY', '', 'editor', '7', 1, 0, 'Waiting List Cancel Notification Email Body'),
(76, 'deposit_payment_form_message', 'EB_DEPOSIT_PAYMENT_FORM_MESSAGE', 'EB_DEPOSIT_PAYMENT_FORM_MESSAGE_EXPLAIN', 'editor', '8', 1, 0, 'Remaining Payment Form Message'),
(77, 'deposit_payment_thanks_message', 'EB_DEPOSIT_PAYMENT_THANK_YOU_MESSAGE', 'EB_DEPOSIT_PAYMENT_THANK_YOU_MESSAGE_EXPLAIN', 'editor', '8', 1, 0, 'Remaining Payment Thank You Message'),
(78, 'deposit_payment_admin_email_subject', 'EB_DEPOSIT_PAYMENT_ADMIN_EMAIL_SUBJECT', '', 'text', '8', 1, 0, 'Remaining Payment Admin Email Subject'),
(79, 'deposit_payment_admin_email_body', 'EB_DEPOSIT_PAYMENT_ADMIN_EMAIL_BODY', '', 'editor', '8', 1, 0, 'Remaining Payment Admin Email Body'),
(80, 'deposit_payment_user_email_subject', 'EB_DEPOSIT_PAYMENT_USER_EMAIL_SUBJECT', '', 'text', '8', 1, 0, 'Remaining Payment User Email Subject'),
(81, 'deposit_payment_user_email_body', 'EB_DEPOSIT_PAYMENT_USER_EMAIL_BODY', '', 'editor', '8', 1, 0, 'Remaining Payment User Email Body'),
(82, 'deposit_payment_reminder_email_subject', 'EB_DEPOSIT_PAYMENT_REMINDER_EMAIL_SUBJECT', '', 'text', '8', 1, 0, 'Deposit Payment Reminder Email Subject'),
(83, 'deposit_payment_reminder_email_body', 'EB_DEPOSIT_PAYMENT_REMINDER_EMAIL_BODY', '', 'editor', '8', 1, 0, 'Deposit Payment Reminder Email Body'),
(84, 'new_registration_admin_sms', 'EB_NEW_REGISTRATION_ADMIN_SMS', '', 'textarea', '9', 1, 0, 'New Registration SMS'),
(85, 'first_reminder_sms', 'EB_FIRST_REMINDER_SMS', '', 'textarea', '9', 1, 0, 'First Reminder SMS'),
(86, 'second_reminder_sms', 'EB_SECOND_REMINDER_SMS', '', 'textarea', '9', 1, 0, 'Second Reminder SMS');